

ALTER TABLE users ADD COLUMN IF NOT EXISTS createdBy UUID REFERENCES users(id);
ALTER TABLE users ADD COLUMN IF NOT EXISTS modifiedBy UUID REFERENCES users(id);
ALTER TABLE users ADD COLUMN IF NOT EXISTS createdOn TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS modifiedOn TIMESTAMP;

ALTER TABLE "order" ADD COLUMN IF NOT EXISTS createdBy UUID REFERENCES users(id);
ALTER TABLE "order" ADD COLUMN IF NOT EXISTS modifiedBy UUID REFERENCES users(id);
ALTER TABLE "order" ADD COLUMN IF NOT EXISTS createdOn TIMESTAMP;
ALTER TABLE "order" ADD COLUMN IF NOT EXISTS modifiedOn TIMESTAMP;
ALTER TABLE "order" DROP COLUMN IF EXISTS user_id;